### ISSUE TITLE
Sometimes the dialog start at 2nd line.

### ISSUE THREAD

**Issue by caogtaa** [caogtaa/newbark#8]

**Comment by route1rodent** [comment]
wow it's great to see you are improving the project ^_^ , is it possible to you to contribute to the main one and open a PR from your master branch to the [original project master branch](https://github.com/route1rodent/newbark)?

you can also open issues there, so we can work in them together. I can also give you contribution rights to that one.

this way we can join efforts :)

what do you think?

PS: there is also an ongoing "refactoring" branch https://github.com/route1rodent/newbark/tree/movementRefactoring

Note that the project has been moved from capsumon to -> route1rodent

**Comment by caogtaa** [comment]
hi, @route1rodent 
This is really good project for beginner to learn all the stuff in classic game, and of course I will PR the improvement to origin main.

Great to see someone is still working on it. 
Any long term target for this project, like battle and story?

**Comment by route1rodent** [comment]
Yes I want to introduce all the basics of the game so it will be like a template. But I am also learning Unity at the same time, that is why I might make mistakes and need help of some more advanced unity game devs :)
You seem more advanced than me and would be nice to have your help.

Take a look to the projects and issues tabs to see all I wanted to introduce and fix:

https://github.com/route1rodent/newbark/projects
https://github.com/route1rodent/newbark/issues

**Comment by route1rodent** [comment]
after fixing and improving some stuff like the move refactoring branch and warping, I would like introduce "movement instruction sets" so we can have NPCs walking around with a predefined path. That's only possible with a better reusable movement code

**Comment by caogtaa** [comment]
hi @route1rodent , I just follow you in twitter.https://twitter.com/caogtaa

**Comment by route1rodent** [comment]
ok better, we can organise this stuff there by messages
